// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiCLwMWBlnBeQGTvKYZLu16EZGxoB_wes',
    appId: '1:839804029521:web:61258d3507b892b0f0c670',
    messagingSenderId: '839804029521',
    projectId: 'cruz-hacks-2025',
    authDomain: 'cruz-hacks-2025.firebaseapp.com',
    storageBucket: 'cruz-hacks-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQqsu7_yZuJq5Hw-G1gLxD5JcCe4P8te0',
    appId: '1:839804029521:android:ff8a061475b3a648f0c670',
    messagingSenderId: '839804029521',
    projectId: 'cruz-hacks-2025',
    storageBucket: 'cruz-hacks-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClELHtng2ZP5Sl-oEOJExQTfPqXzPnLck',
    appId: '1:839804029521:ios:227ece714a7b0cb8f0c670',
    messagingSenderId: '839804029521',
    projectId: 'cruz-hacks-2025',
    storageBucket: 'cruz-hacks-2025.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClELHtng2ZP5Sl-oEOJExQTfPqXzPnLck',
    appId: '1:839804029521:ios:227ece714a7b0cb8f0c670',
    messagingSenderId: '839804029521',
    projectId: 'cruz-hacks-2025',
    storageBucket: 'cruz-hacks-2025.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiCLwMWBlnBeQGTvKYZLu16EZGxoB_wes',
    appId: '1:839804029521:web:1c2e9e9ba7bfbd82f0c670',
    messagingSenderId: '839804029521',
    projectId: 'cruz-hacks-2025',
    authDomain: 'cruz-hacks-2025.firebaseapp.com',
    storageBucket: 'cruz-hacks-2025.firebasestorage.app',
  );
}
